version: 'python:3.9-slim'
services:
  streamlit:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: rush-blog
    cpus: 0.5
    mem_limit: 1024m
    ports:
      - "8501:8501"
    volumes:
      - ".:/app:rw"